version: '3'

services:
  db:
    container_name: 'backoffice-db'
    image: postgres:alpine
    environment:
      POSTGRES_PASSWORD: docker
      POSTGRES_USER: docker
      POSTGRES_DB: backoffice
      PGDATA: /var/lib/postgresql/data
    ports:
      - '5432:5432'
    volumes:
      - backoffice-data:/var/lib/postgresql/data


volumes:
  backoffice-data:
