version: '3'

services:
  postgres:
    container_name: backoffice-postgres
    image: postgres:15
    environment:
      DATABASE_HOST: localhost
      POSTGRES_PASSWORD: docker
      POSTGRES_USER: docker
      POSTGRES_DB: backoffice
      PG_DATA: /var/lib/postgresql/data
    ports:
      - "5432:5432"
    volumes:
      - pgdata-backoffice:/var/lib/postgresql/data

volumes:
  pgdata-backoffice:
